# yaml-language-server: $schema=../../schema/template.schema.json
name: '2048'
description: Browser-based 2048 puzzle game server
variables: []
game_id: 2048
docker_image_name: alexwhen/docker-2048
docker_image_tag: latest
environment_variables: {}
port_mapping:
  '8080/tcp': 8080
file_mounts: []
file_downloads: []
resource_limit:
  memory: 128M
  cpu: 0.5
